[2024-09-25T14:00:07.525+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T14:00:07.533+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: name_of_pipeline.choose_branch manual__2024-09-25T14:00:03.675371+00:00 [queued]>
[2024-09-25T14:00:07.538+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: name_of_pipeline.choose_branch manual__2024-09-25T14:00:03.675371+00:00 [queued]>
[2024-09-25T14:00:07.538+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-25T14:00:07.544+0000] {taskinstance.py:2888} INFO - Executing <Task(_BranchPythonDecoratedOperator): choose_branch> on 2024-09-25 14:00:03.675371+00:00
[2024-09-25T14:00:07.547+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1717) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T14:00:07.548+0000] {standard_task_runner.py:72} INFO - Started process 1719 to run task
[2024-09-25T14:00:07.549+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'name_of_pipeline', 'choose_branch', 'manual__2024-09-25T14:00:03.675371+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_reload.py', '--cfg-path', '/tmp/tmphxxyu1wb']
[2024-09-25T14:00:07.550+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask choose_branch
[2024-09-25T14:00:07.572+0000] {task_command.py:467} INFO - Running <TaskInstance: name_of_pipeline.choose_branch manual__2024-09-25T14:00:03.675371+00:00 [running]> on host f40d972903b2
[2024-09-25T14:00:07.612+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='name_of_pipeline' AIRFLOW_CTX_TASK_ID='choose_branch' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T14:00:03.675371+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T14:00:03.675371+00:00'
[2024-09-25T14:00:07.614+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-25T14:00:07.615+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-25T14:00:07.615+0000] {logging_mixin.py:190} INFO - Current task name:choose_branch state:running start_date:2024-09-25 14:00:07.534237+00:00
[2024-09-25T14:00:07.615+0000] {logging_mixin.py:190} INFO - Dag name:name_of_pipeline and current dag run status:running
[2024-09-25T14:00:07.615+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T14:00:07.616+0000] {python.py:240} INFO - Done. Returned value was: task4
[2024-09-25T14:00:07.618+0000] {branch.py:38} INFO - Branch into task4
[2024-09-25T14:00:07.619+0000] {skipmixin.py:230} INFO - Following branch ('task4',)
[2024-09-25T14:00:07.627+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 40, in do_branch
    self.skip_all_except(context["ti"], branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 189, in skip_all_except
    SkipMixin._skip_all_except(ti=ti, branch_task_ids=branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 243, in _skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'task4'}.
[2024-09-25T14:00:07.632+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-25T14:00:07.633+0000] {logging_mixin.py:190} INFO - Task start:2024-09-25 14:00:07.534237+00:00 end:2024-09-25 14:00:07.631973+00:00 duration:0.097736
[2024-09-25T14:00:07.633+0000] {logging_mixin.py:190} INFO - Task:<Task(_BranchPythonDecoratedOperator): choose_branch> dag:<DAG: name_of_pipeline> dagrun:<DagRun name_of_pipeline @ 2024-09-25 14:00:03.675371+00:00: manual__2024-09-25T14:00:03.675371+00:00, state:running, queued_at: 2024-09-25 14:00:03.698030+00:00. externally triggered: True>
[2024-09-25T14:00:07.634+0000] {logging_mixin.py:190} INFO - Failure caused by 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'task4'}.
[2024-09-25T14:00:07.634+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=name_of_pipeline, task_id=choose_branch, run_id=manual__2024-09-25T14:00:03.675371+00:00, execution_date=20240925T140003, start_date=20240925T140007, end_date=20240925T140007
[2024-09-25T14:00:07.639+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T14:00:07.640+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task choose_branch ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'task4'}.; 1719)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 40, in do_branch
    self.skip_all_except(context["ti"], branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 189, in skip_all_except
    SkipMixin._skip_all_except(ti=ti, branch_task_ids=branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 243, in _skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'task4'}.
[2024-09-25T14:00:07.687+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-25T14:00:07.706+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T14:00:07.731+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
